variables:
  IMAGE_NAME: "docker.io/tchofo/alpinehelloworld" 
  INTERNAL_PORT: 5000
  EXTERNAL_PORT: 80

stages:
  - build
  - test_acceptation
  - release_image

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts:
    paths:
      - alpinehelloworld.tar

test_acceptation:
  image: docker:latest
  stage: test_acceptation
  services:
    - docker:dind
  script:
    - docker load < alpinehelloworld.tar
    - docker run -d -p $EXTERNAL_PORT:$INTERNAL_PORT -e PORT=$INTERNAL_PORT --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker" | grep "Hello world!"

release_image:
  image: docker:latest
  stage: release_image
  services:
    - docker:dind
  script:
    - docker load < alpinehelloworld.tar  # Charger l'image Docker sauvegardée
    - docker images  # Vérifier les images Docker disponibles
    - docker tag alpinehelloworld "docker.io/$DOCKER_USERNAME/alpinehelloworld:${CI_COMMIT_REF_NAME}"  # Taguer l'image
    - docker tag alpinehelloworld "docker.io/$DOCKER_USERNAME/alpinehelloworld:${CI_COMMIT_SHORT_SHA}"  # Taguer l'image avec le hash du commit
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin  # Se connecter à DockerHub
    - docker push "docker.io/$DOCKER_USERNAME/alpinehelloworld:${CI_COMMIT_REF_NAME}"  # Pousser l'image avec le tag de la branche
    - docker push "docker.io/$DOCKER_USERNAME/alpinehelloworld:${CI_COMMIT_SHORT_SHA}"  # Pousser l'image avec le tag du commit
  only:
    - master