variables:
  IMAGE_NAME: "dockerhub_username/alpinehelloworld"  # Mettez à jour avec votre nom d'image DockerHub
  INTERNAL_PORT: 5000
  EXTERNAL_PORT: 80

stages:
  - build
  - test_acceptation
  - release_image

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts:
    paths:
      - alpinehelloworld.tar

test_acceptation:
  image: docker:latest
  stage: test_acceptation
  services:
    - docker:dind
  script:
    - docker load < alpinehelloworld.tar
    - docker run -d -p $EXTERNAL_PORT:$INTERNAL_PORT -e PORT=$INTERNAL_PORT --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker" | grep "Hello world!"

release_image:
  image: docker:latest
  stage: release_image
  services:
    - docker:dind
  script:
    - docker load < alpinehelloworld.tar
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
  only:
    - master