
image: docker:latest
services:
  - name: docker:dind 


stages:
  - build
  - Test acceptation


docker-build:
  stage: build 
  script:
    - docker build -t alpinehelloworld .

test acceptation:
  stage: Test acceptation
  script:
    - docker run -d -p 80:5000 -e PORT=5000 --name webapp alpinehelloworld
    - curl "http://docker" | grep "hello world"